config/routes.rb
Rails.application.routes.draw do
  # require "admin_constraint"
  # mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new
  mount Ckeditor::Engine => "/ckeditor"
  
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  # devise_for :users
  devise_for :users, controlllers: {registrations: "registrations"}

  # devise_scope :user do 
  #   get "/admin" => "devise/sessions#new" 

  root 'pages#home'
  # match '/our-events' =>               'events#our_events',             via: ['get'],          :as => 'our_events'
  # match '/events/houston' =>               'events#houston',             via: ['get'],          :as => 'houston'
  # match '/events/austin' =>               'events#austin',             via: ['get'],          :as => 'austin'
  # match '/events/orlando' =>               'events#orlando',             via: ['get'],          :as => 'orlando'
  # match '/events/atlanta' =>               'events#atlanta',             via: ['get'],          :as => 'atlanta'
  # match '/events/cincinnati' =>               'events#cincinnati',             via: ['get'],          :as => 'cincinnati'
  # match '/events/dc' =>               'events#dc',             via: ['get'],          :as => 'dc'
  # match '/events/philadelphia' =>               'events#philadelphia',             via: ['get'],          :as => 'philadelphia'
  # match '/events/pittsburgh' =>               'events#pittsburgh',             via: ['get'],          :as => 'pittsburgh'
  # match '/events/salt-lake-city' =>               'events#saltlakecity',             via: ['get'],          :as => 'saltlakecity'
  # match '/events/south-florida' =>               'events#southflorida',             via: ['get'],          :as => 'southflorida'
  # match '/events/tampa-bay' =>               'events#tampabay',             via: ['get'],          :as => 'tampabay'

  match '/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
  match '/about-amy' =>                 'pages#about_amy',               via: ['get'],          :as => 'pages_about_amy'
  match '/partner-with-us' =>                      'pages#partner_with_us',         via: ['get'],          :as => 'pages_partner_with_us'

  match "/contacts"              =>        "contacts#create",              via: [:post]

  resources :users, except: [:create, :update]
  post 'create_user' => 'users#create', as: :create_user
  patch 'update_user/:id' => 'users#update', as: :update_user


  #########################################
  #==blogs url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    get "/blogs/categories", to: "blogs#index"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"

    get "blogs/categories/:category_slug", to: "blogs#index_category", as: "index_category"

  #########################################
  #==press url for press model
  #########################################
    # get "/press", to: "press#index", as: :press_index
    get "/press", to: "press#press_page", as: :press_page
    get "press/:title_for_slug", to: "press#show", as: "press"

  #########################################
  #==events url for events model
  #########################################
    get "/events", to: "events#index", as: :events
    get "events/:title_for_slug", to: "events#show", as: "event"
  
  #########################################
  #==partners url for partner model
  #########################################
    # get "/featured-partners", to: "partners#featured_partners"

    get "/partners", to: "partners#index", as: :partners
    get "/partners/:title_for_slug", to: "partners#show", as: :partner


    # get "/partners/la-croix", to: "partners#la_croix", as: :la_croix
    # get "/partners/cribs-for-kids", to: "partners#cribs_for_kids", as: :cribs_for_kids

    # get "partners/:title_for_slug", to: "partners#show", as: "partner"





  # match '/events'              =>        'events#index',              via: [:get],            :as => 'events'
  # match '/events/show'              =>        'events#show',              via: [:get],            :as => 'event'






  ############## ADMIN SECTION ############

  namespace :admin do
      match '/' =>                                'pages#admin',             via: ['get'],          :as => 'pages_admin'

      match '/pages/home' =>                      'pages#home',             via: ['get'],          :as => 'pages_home'
      match '/pages/home/update' =>                      'pages#home_update',             via: ['patch'],          :as => 'pages_home_update'
      match '/pages/home/delete_home_page_bottom_ad_one' =>                      'pages#delete_home_page_bottom_ad_one',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_one'
      match '/pages/home/delete_home_page_bottom_ad_two' =>                      'pages#delete_home_page_bottom_ad_two',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_two'
      match '/pages/home/delete_home_page_bottom_ad_three' =>                      'pages#delete_home_page_bottom_ad_three',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_three'


      match '/pages/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
      match '/pages/about-moabs/update' =>               'pages#about_moabs_update',             via: ['patch'],          :as => 'pages_about_moabs_update'


      match '/pages/about-amy' =>                 'pages#about_amy',             via: ['get'],          :as => 'pages_about_amy'
      match '/pages/about-amy/update' =>                 'pages#about_amy_update',             via: ['patch'],          :as => 'pages_about_amy_update'
      match '/pages/about-amy/delete_about_amy_bottom_ad_one' =>                      'pages#delete_about_amy_bottom_ad_one',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_one'
      match '/pages/about-amy/delete_about_amy_bottom_ad_two' =>                      'pages#delete_about_amy_bottom_ad_two',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_two'
      match '/pages/about-amy/delete_about_amy_bottom_ad_three' =>                      'pages#delete_about_amy_bottom_ad_three',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_three'



      match '/pages/partner-with-us' =>                      'pages#partner_with_us',             via: ['get'],          :as => 'pages_partner_with_us'
      match '/pages/partner-with-us/update' =>                      'pages#partner_with_us_update',             via: ['patch'],          :as => 'pages_partner_with_us_update'


      match '/event_index_images' =>                                       'events#edit_images',             via: ['get'],          :as => 'event_index_images'
      match '/event_index_images/update' =>                                'events#update_images',             via: ['patch'],          :as => 'event_index_images_update'


      match 'event_index_images/delete_event_index_bottom_ad_one'               => 'events#delete_event_index_bottom_ad_one',        :via => [:delete],        :as => :delete_event_index_bottom_ad_one
      match 'event_index_images/delete_event_index_bottom_ad_two'               => 'events#delete_event_index_bottom_ad_two',        :via => [:delete],        :as => :delete_event_index_bottom_ad_two
      match 'event_index_images/delete_event_index_bottom_ad_three'               => 'events#delete_event_index_bottom_ad_three',        :via => [:delete],        :as => :delete_event_index_bottom_ad_three
      match 'event_index_images/delete_event_index_side_ad_one'                     => 'events#delete_event_index_side_ad_one',              :via => [:delete],        :as => :delete_event_index_side_ad_one
      match 'event_index_images/delete_event_index_side_ad_two'                     => 'events#delete_event_index_side_ad_two',              :via => [:delete],        :as => :delete_event_index_side_ad_two





      match '/blog_index_images' =>                                       'blogs#edit_images',             via: ['get'],          :as => 'blog_index_images'
      match '/blog_index_images/update' =>                                'blogs#update_images',             via: ['patch'],          :as => 'blog_index_images_update'

      match 'blog_index_images/delete_blogs_index_bottom_ad_one'               => 'blogs#delete_blogs_index_bottom_ad_one',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_one
      match 'blog_index_images/delete_blogs_index_bottom_ad_two'               => 'blogs#delete_blogs_index_bottom_ad_two',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_two
      match 'blog_index_images/delete_blogs_index_bottom_ad_three'               => 'blogs#delete_blogs_index_bottom_ad_three',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_three
      match 'blog_index_images/delete_blogs_index_side_ad'                     => 'blogs#delete_blogs_index_side_ad',              :via => [:delete],        :as => :delete_blogs_index_side_ad

      match '/press_index_images' =>                                       'press#edit_images',             via: ['get'],          :as => 'press_index_images'
      match '/press_index_images/update' =>                                'press#update_images',             via: ['patch'],          :as => 'press_index_images_update'

      match '/edit_press_page' =>                                       'press#edit_press_page',             via: ['get'],          :as => 'edit_press_page'
      match '/update_press_page' =>                                'press#update_press_page',             via: ['patch'],          :as => 'update_press_page'

app/views/admin/pages/_about_moab_image.html.erb
<% if img.id.present? %>
<div id="about_moab_image_<%= img.id %>" class="col-md-4 col-sm-6 item-img mb20" style="position: relative;">
  <img src="<%= img.pic.url(:medium) %>" alt="" class="img-responsive" width="100%" />
  <%= link_to "X", admin_about_moab_image_delete_path(img.id.to_s),:method=>'delete', style: "position: absolute; top: 0px; right: 24px; color: red; font-size: 24px;", :remote=>true,:data=>{:confirm=>"Are you sure?"} %>
</div>
<% end %>

app/views/admin/pages/_partner_with_u_image.html.erb
<% if img.id.present? %>
<div id="partner_with_u_image_<%= img.id %>" class="col-md-4 col-sm-6 item-img mb20" style="position: relative;">
  <img src="<%= img.pic.url(:medium) %>" alt="" class="img-responsive" width="100%" />
  <%= link_to "X", admin_partner_with_u_image_delete_path(img.id.to_s),:method=>'delete', style: "position: absolute; top: 0px; right: 24px; color: red; font-size: 24px;", :remote=>true,:data=>{:confirm=>"Are you sure?"} %>
</div>
<% end %>

app/views/admin/pages/about_amy.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Edit About Amy Page</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">
              <%= form_for(@about_amy, :url => admin_pages_about_amy_update_url, :html => { :multipart => true }) do |f| %>
                <% if @about_amy.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@about_amy.errors.count, "error") %> prohibited this Event Index Image from being saved:</h2>

                    <ul>
                    <% @about_amy.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>


                <div class="form-group">
                  <%= f.label :background_img %>
                  <%= "<br>".html_safe if @about_amy.background_img.present? %>
                  <%= image_tag(@about_amy.background_img.url(:large), width: "180px") if @about_amy.background_img.present? %>
                  <%= "<br><br>".html_safe if @about_amy.background_img.present? %>                  
                  <%= f.file_field :background_img, class: "form-control" %>
                </div>
                
                <div class="form-group">
                  <%= f.label :meet_amy %>
                  <%= f.cktext_area :meet_amy, class: "form-control ckeditor" %>
                </div>

                <div class="form-group">
                  <%= f.label :moabs_experience %>
                  <%= f.cktext_area :moabs_experience, class: "form-control ckeditor" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_one_link %>
                  <%= f.text_field :bottom_ad_one_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_one %>
                  <%= "<br>".html_safe if @about_amy.bottom_ad_one.present? %>
                  <%= image_tag(@about_amy.bottom_ad_one.url(:medium), width: "180px") if @about_amy.bottom_ad_one.present? %>
                  <%= "<br><br>".html_safe if @about_amy.bottom_ad_one.present? %>
                  <%= f.file_field :bottom_ad_one, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two_link %>
                  <%= f.text_field :bottom_ad_two_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two %>
                  <%= "<br>".html_safe if @about_amy.bottom_ad_two.present? %>
                  <%= image_tag(@about_amy.bottom_ad_two.url(:medium), width: "180px") if @about_amy.bottom_ad_two.present? %>
                  <%= "<br><br>".html_safe if @about_amy.bottom_ad_two.present? %>                  
                  <%= f.file_field :bottom_ad_two, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three_link %>
                  <%= f.text_field :bottom_ad_three_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three %>
                  <%= "<br>".html_safe if @about_amy.bottom_ad_three.present? %>
                  <%= image_tag(@about_amy.bottom_ad_three.url(:medium), width: "180px") if @about_amy.bottom_ad_three.present? %>
                  <%= "<br><br>".html_safe if @about_amy.bottom_ad_three.present? %>
                  <%= f.file_field :bottom_ad_three, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_title %>
                  <%= f.text_field :meta_title, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_description %>
                  <%= f.text_field :meta_description, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>

          <div class="row mt70">
            <div class="col-md-4" style="position: relative;">
              <p><%= "Bottom ad one" if @about_amy.bottom_ad_one.present? %></p>
              <%= image_tag(@about_amy.bottom_ad_one.url(:medium), class: "img-responsive", width: '100%') if @about_amy.bottom_ad_one.present? %>
              <span class="fts20 color-red" style="position: absolute; top: 20px; right:22px; color: red;"><%= link_to 'X', admin_delete_about_amy_bottom_ad_one_path, style: "color: red;", method: :delete if @about_amy.bottom_ad_one.present? %></span>
              <br><br>
            </div>
            <div class="col-md-4" style="position: relative;">
              <p><%= "Bottom ad two" if @about_amy.bottom_ad_two.present? %></p>
              <%= image_tag(@about_amy.bottom_ad_two.url(:medium), class: "img-responsive", width: '100%') if @about_amy.bottom_ad_two.present? %>
              <span class="fts20 color-red" style="position: absolute; top: 20px; right:22px; color: red;"><%= link_to 'X', admin_delete_about_amy_bottom_ad_two_path, style: "color: red;", method: :delete if @about_amy.bottom_ad_two.present? %></span>
              <br><br>
            </div>
            <div class="col-md-4" style="position: relative;">
              <p><%= "Bottom ad three" if @about_amy.bottom_ad_three.present? %></p>
              <%= image_tag(@about_amy.bottom_ad_three.url(:medium), class: "img-responsive", width: '100%') if @about_amy.bottom_ad_three.present? %>
              <span class="fts20 color-red" style="position: absolute; top: 20px; right:22px; color: red;"><%= link_to 'X', admin_delete_about_amy_bottom_ad_three_path, style: "color: red;", method: :delete if @about_amy.bottom_ad_three.present? %></span>
              <br><br>
            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/pages/about_amy_image_create.js.erb
<% if @about_amy_image.errors.any? %>
  alert("Failed to upload picture: <%= j @about_amy_image.errors.full_messages.join(', ').html_safe %>");
<% else %>
  <% @about_amy_image.position = Image.where(imageable_type: 'AboutAmy', imageable_id: @about_amy.id).maximum(:position).to_i + 1 %>
  <% @about_amy_image.save %>
  // The issue seems to be when uploading multiple files at once, their positions are all being the same
  // Unfortunately this is the only way i could get the position of the image uploaded to increment and be correct, 
  // I tried putting the code above in before_create and after_create, before_save and after_save callbacks as well as putting the code in the controller but no luck.

  $('#new_about_amy_asset')[0].reset() // basically reset the form
  $('#about_amy_images').append('<%= j render :partial => "about_amy_image", locals: {img: @about_amy_image}  %>')
  // Here you are appending the new images created (@about_amy_image from controller create action) to your exisitng images, hence img: @about_amy_image
  // remember fileupload submits the form for each image. Therefore each image uploaded will go through the create action and therefore through this create.js.erb template
  // So for example if you upload 3 images, you will see this render action in your logs 3 times.
<% end %>

app/views/admin/pages/about_amy_image_delete.js.erb
    $("#about_amy_image_<%= @about_amy_image.id %>").remove();

app/views/admin/pages/about_moab_images.html.erb
    <div class="wrapper">

        <%= render 'admin/layouts/sidebar' %>
        
        <div id="content">

            <%= render 'admin/layouts/sidebar_topnav' %>
               
                <div class="row">

                    <div class="col-sm-12 text-center mb35">

                        <h1 class="mb30">About Moabs Slideshow Images</h1>

                        <%= form_for(@about_moab_image, url:  admin_about_moab_image_create_path, :html => { :multipart => true }) do |f| %>
                          <% if @about_moab_image.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(@about_moab_image.errors.count, "error") %> prohibited this gallery image from being saved:</h2>
                              <ul>
                              <% @about_moab_image.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>

                          <div class="form-group">
                            <%= f.hidden_field :imageable_type, value: 'AboutMoab'  %>
                            <%= f.hidden_field :imageable_id, value: @about_moab.id  %>
                            <div class="dropzone" id="about_moab_dropzone">
                              <%= f.label :pic, "Add Images", class: "btn btn-primary" %>
                              <%= f.file_field :pic, multiple: true, name: "about_moab_image[pic]", class: "hide", required: true %>  
                            </div>
                          </div>

                          <!-- This is the progress bar showing the upload -->
                          <script id="template-upload" type="text/x-tmpl">
                            <div class="upload">
                              {%= "Uploading " + o.name + " (this bar will disappear once upload is complete)"%}
                              <div class="progress"><div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:0%;"></div></div>
                            </div>
                          </script>

                          <div class="form-group">
                            <%= f.submit "Upload", class: "form-control btn btn-primary hide" %>
                          </div>
                        <% end %>

                      </div>

                      <div id="about_moab_images" data-update-url="<%= admin_about_moab_image_sort_path %>">
                        <% @about_moab_images.each do | img | %>
                          <%= render partial: 'about_moab_image', locals: {img: img} %>
                        <% end %>
                      </div>

              </div>

        </div> <!-- content  -->

    </div> <!-- wrapper  -->


    <%= render 'admin/layouts/sidebar_styles_scripts' %>


    <style>
      .dropzone {
        text-align: center;
        /*margin-top: 20px;*/
        padding-top: 30px;
        padding-bottom: 30px;
         border: 2px dashed #ddd;
      }
      .hide {
        display: none;
      }
      #about_moab_images img:hover {
        cursor: move;
      }
      .x_delete:hover {
        cursor: pointer;
      }
    </style>

app/views/admin/pages/home_page_image_delete.js.erb
    $("#home_page_image_<%= @home_page_image.id %>").remove();

app/views/admin/pages/home_page_images.html.erb
    <div class="wrapper">

        <%= render 'admin/layouts/sidebar' %>
        
        <div id="content">

            <%= render 'admin/layouts/sidebar_topnav' %>
               
                <div class="row">

                    <div class="col-sm-12 text-center mb35">

                        <h1 class="mb30">Home Page Slideshow Images</h1>

                        <%= form_for(@home_page_image, url:  admin_home_page_image_create_path, :html => { :multipart => true }) do |f| %>
                          <% if @home_page_image.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(@home_page_image.errors.count, "error") %> prohibited this gallery image from being saved:</h2>
                              <ul>
                              <% @home_page_image.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>

                          <div class="form-group">
                            <%= f.hidden_field :imageable_type, value: 'HomePage'  %>
                            <%= f.hidden_field :imageable_id, value: @home_page.id  %>
                            <div class="dropzone" id="home_page_dropzone">
                              <%= f.label :pic, "Add Images", class: "btn btn-primary" %>
                              <%= f.file_field :pic, multiple: true, name: "home_page_image[pic]", class: "hide", required: true %>  
                            </div>
                          </div>

                          <!-- This is the progress bar showing the upload -->
                          <script id="template-upload" type="text/x-tmpl">
                            <div class="upload">
                              {%= "Uploading " + o.name + " (this bar will disappear once upload is complete)"%}
                              <div class="progress"><div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:0%;"></div></div>
                            </div>
                          </script>

                          <div class="form-group">
                            <%= f.submit "Upload", class: "form-control btn btn-primary hide" %>
                          </div>
                        <% end %>

                      </div>

                      <div id="home_page_images" data-update-url="<%= admin_home_page_image_sort_path %>">
                        <% @home_page_images.each do | img | %>
                          <%= render partial: 'home_page_image', locals: {img: img} %>
                        <% end %>
                      </div>

              </div>

        </div> <!-- content  -->

    </div> <!-- wrapper  -->


    <%= render 'admin/layouts/sidebar_styles_scripts' %>


    <style>
      .dropzone {
        text-align: center;
        /*margin-top: 20px;*/
        padding-top: 30px;
        padding-bottom: 30px;
         border: 2px dashed #ddd;
      }
      .hide {
        display: none;
      }
      #home_page_images img:hover {
        cursor: move;
      }
      .x_delete:hover {
        cursor: pointer;
      }
    </style>

app/views/admin/pages/images.html.erb
    <div class="wrapper">

        <%= render 'admin/layouts/sidebar' %>
        
        <div id="content">

            <%= render 'admin/layouts/sidebar_topnav' %>
         
              <div>

                  <div class="row mt20">
                      <div class="col-md-3 col-sm-4">
                        <%= image_tag(@home_page.main_image.url(:medium), class:'img-responsive') %>
                      </div>

                      <div class="col-md-9 col-sm-8">
                        <h4 class="">Home Page</h4>
                        <%= link_to 'Edit Image Slides', admin_home_page_image_path, class:"btn btn-warning" %>
                      </div>
                  </div>
                  <hr>
                  <div class="row mt20">
                      <div class="col-md-3 col-sm-4">
                        <%= image_tag(@about_moabs.main_image.url(:medium), class:'img-responsive') %>
                      </div>

                      <div class="col-md-9 col-sm-8">
                        <h4 class="">About Moabs</h4>
                        <%= link_to 'Edit Image Slides', admin_about_moab_image_path, class:"btn btn-warning" %>
                      </div>
                  </div>
                  <hr>
                  <div class="row mt20">
                      <div class="col-md-3 col-sm-4">
                        <%= image_tag(@about_amy.background_img.url(:large), class:'img-responsive') %>
                      </div>

                      <div class="col-md-9 col-sm-8">
                        <h4 class="">About Amy</h4>
                        <%= link_to 'Edit Image Slides 1', admin_about_amy_image_path, class:"btn btn-warning" %>
                        <%= link_to 'Edit Image Slides 2', admin_about_amy_image_path(slider: "2"), class:"btn btn-warning" %>
                      </div>
                  </div>
                  <hr>
                  <div class="row mt20">
                      <div class="col-md-3 col-sm-4">
                        <%= image_tag(@partner_with_us.main_image.url(:medium), class:'img-responsive') %>
                      </div>

                      <div class="col-md-9 col-sm-8">
                        <h4 class="">Partner With Us</h4>
                        <%= link_to 'Edit Image Slides', admin_partner_with_u_image_path, class:"btn btn-warning" %>
                      </div>
                  </div>
                  <hr>
                  <div class="row mt20">
                      <div class="col-md-3 col-sm-4">
                        <%= image_tag(@press_page.main_image.url(:medium), class:'img-responsive') %>
                      </div>

                      <div class="col-md-9 col-sm-8">
                        <h4 class="">Press</h4>
                        <%= link_to 'Edit Image Gallery', admin_press_images_path, class:"btn btn-warning" %>
                      </div>
                  </div>
                  <hr>

              </div>
            

        </div> <!-- content  -->

    </div> <!-- wrapper  -->


    <%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/pages/partner_with_u_image_delete.js.erb
    $("#partner_with_u_image_<%= @partner_with_u_image.id %>").remove();

app/views/admin/pages/partner_with_us.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Edit Partner With Us Page</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">
              <%= form_for(@partner_with_us, :url => admin_pages_partner_with_us_update_url, :html => { :multipart => true }) do |f| %>
                <% if @partner_with_us.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@partner_with_us.errors.count, "error") %> prohibited this Event Index Image from being saved:</h2>

                    <ul>
                    <% @partner_with_us.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>


                <div class="form-group">
                  <%= f.label :main_image %>
                  <%= "<br>".html_safe if @partner_with_us.main_image.present? %>
                  <%= image_tag(@partner_with_us.main_image.url(:medium), width: "180px") if @partner_with_us.main_image.present? %>
                  <%= "<br><br>".html_safe if @partner_with_us.main_image.present? %>                  
                  <%= f.file_field :main_image, class: "form-control" %>
                </div>
                
                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.cktext_area :description, class: "form-control ckeditor" %>
                </div>

                <div class="form-group">
                  <%= f.label :testimonial %>
                  <%= f.text_field :testimonial, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :testimonial_author %>
                  <%= f.text_field :testimonial_author, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_title %>
                  <%= f.text_field :meta_title, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_description %>
                  <%= f.text_field :meta_description, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>