config/routes.rb
Rails.application.routes.draw do
  # require "admin_constraint"
  # mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new
  mount Ckeditor::Engine => "/ckeditor"
  
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  # devise_for :users
  devise_for :users, controlllers: {registrations: "registrations"}

  # devise_scope :user do 
  #   get "/admin" => "devise/sessions#new" 

  root 'pages#home'
  # match '/our-events' =>               'events#our_events',             via: ['get'],          :as => 'our_events'
  # match '/events/houston' =>               'events#houston',             via: ['get'],          :as => 'houston'
  # match '/events/austin' =>               'events#austin',             via: ['get'],          :as => 'austin'
  # match '/events/orlando' =>               'events#orlando',             via: ['get'],          :as => 'orlando'
  # match '/events/atlanta' =>               'events#atlanta',             via: ['get'],          :as => 'atlanta'
  # match '/events/cincinnati' =>               'events#cincinnati',             via: ['get'],          :as => 'cincinnati'
  # match '/events/dc' =>               'events#dc',             via: ['get'],          :as => 'dc'
  # match '/events/philadelphia' =>               'events#philadelphia',             via: ['get'],          :as => 'philadelphia'
  # match '/events/pittsburgh' =>               'events#pittsburgh',             via: ['get'],          :as => 'pittsburgh'
  # match '/events/salt-lake-city' =>               'events#saltlakecity',             via: ['get'],          :as => 'saltlakecity'
  # match '/events/south-florida' =>               'events#southflorida',             via: ['get'],          :as => 'southflorida'
  # match '/events/tampa-bay' =>               'events#tampabay',             via: ['get'],          :as => 'tampabay'

  match '/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
  match '/about-amy' =>                 'pages#about_amy',               via: ['get'],          :as => 'pages_about_amy'
  match '/partner-with-us' =>                      'pages#partner_with_us',         via: ['get'],          :as => 'pages_partner_with_us'

  match "/contacts"              =>        "contacts#create",              via: [:post]

  resources :users, except: [:create, :update]
  post 'create_user' => 'users#create', as: :create_user
  patch 'update_user/:id' => 'users#update', as: :update_user


  #########################################
  #==blogs url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    get "/blogs/categories", to: "blogs#index"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"

    get "blogs/categories/:category_slug", to: "blogs#index_category", as: "index_category"

  #########################################
  #==press url for press model
  #########################################
    # get "/press", to: "press#index", as: :press_index
    get "/press", to: "press#press_page", as: :press_page
    get "press/:title_for_slug", to: "press#show", as: "press"

  #########################################
  #==events url for events model
  #########################################
    get "/events", to: "events#index", as: :events
    get "events/:title_for_slug", to: "events#show", as: "event"
  
  #########################################
  #==partners url for partner model
  #########################################
    # get "/featured-partners", to: "partners#featured_partners"

    get "/partners", to: "partners#index", as: :partners
    get "/partners/:title_for_slug", to: "partners#show", as: :partner


    # get "/partners/la-croix", to: "partners#la_croix", as: :la_croix
    # get "/partners/cribs-for-kids", to: "partners#cribs_for_kids", as: :cribs_for_kids

    # get "partners/:title_for_slug", to: "partners#show", as: "partner"





  # match '/events'              =>        'events#index',              via: [:get],            :as => 'events'
  # match '/events/show'              =>        'events#show',              via: [:get],            :as => 'event'






  ############## ADMIN SECTION ############

  namespace :admin do
      match '/' =>                                'pages#admin',             via: ['get'],          :as => 'pages_admin'

      match '/pages/home' =>                      'pages#home',             via: ['get'],          :as => 'pages_home'
      match '/pages/home/update' =>                      'pages#home_update',             via: ['patch'],          :as => 'pages_home_update'
      match '/pages/home/delete_home_page_bottom_ad_one' =>                      'pages#delete_home_page_bottom_ad_one',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_one'
      match '/pages/home/delete_home_page_bottom_ad_two' =>                      'pages#delete_home_page_bottom_ad_two',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_two'
      match '/pages/home/delete_home_page_bottom_ad_three' =>                      'pages#delete_home_page_bottom_ad_three',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_three'


      match '/pages/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
      match '/pages/about-moabs/update' =>               'pages#about_moabs_update',             via: ['patch'],          :as => 'pages_about_moabs_update'


      match '/pages/about-amy' =>                 'pages#about_amy',             via: ['get'],          :as => 'pages_about_amy'
      match '/pages/about-amy/update' =>                 'pages#about_amy_update',             via: ['patch'],          :as => 'pages_about_amy_update'
      match '/pages/about-amy/delete_about_amy_bottom_ad_one' =>                      'pages#delete_about_amy_bottom_ad_one',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_one'
      match '/pages/about-amy/delete_about_amy_bottom_ad_two' =>                      'pages#delete_about_amy_bottom_ad_two',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_two'
      match '/pages/about-amy/delete_about_amy_bottom_ad_three' =>                      'pages#delete_about_amy_bottom_ad_three',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_three'



      match '/pages/partner-with-us' =>                      'pages#partner_with_us',             via: ['get'],          :as => 'pages_partner_with_us'
      match '/pages/partner-with-us/update' =>                      'pages#partner_with_us_update',             via: ['patch'],          :as => 'pages_partner_with_us_update'


      match '/event_index_images' =>                                       'events#edit_images',             via: ['get'],          :as => 'event_index_images'
      match '/event_index_images/update' =>                                'events#update_images',             via: ['patch'],          :as => 'event_index_images_update'


      match 'event_index_images/delete_event_index_bottom_ad_one'               => 'events#delete_event_index_bottom_ad_one',        :via => [:delete],        :as => :delete_event_index_bottom_ad_one
      match 'event_index_images/delete_event_index_bottom_ad_two'               => 'events#delete_event_index_bottom_ad_two',        :via => [:delete],        :as => :delete_event_index_bottom_ad_two
      match 'event_index_images/delete_event_index_bottom_ad_three'               => 'events#delete_event_index_bottom_ad_three',        :via => [:delete],        :as => :delete_event_index_bottom_ad_three
      match 'event_index_images/delete_event_index_side_ad_one'                     => 'events#delete_event_index_side_ad_one',              :via => [:delete],        :as => :delete_event_index_side_ad_one
      match 'event_index_images/delete_event_index_side_ad_two'                     => 'events#delete_event_index_side_ad_two',              :via => [:delete],        :as => :delete_event_index_side_ad_two





      match '/blog_index_images' =>                                       'blogs#edit_images',             via: ['get'],          :as => 'blog_index_images'
      match '/blog_index_images/update' =>                                'blogs#update_images',             via: ['patch'],          :as => 'blog_index_images_update'

      match 'blog_index_images/delete_blogs_index_bottom_ad_one'               => 'blogs#delete_blogs_index_bottom_ad_one',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_one
      match 'blog_index_images/delete_blogs_index_bottom_ad_two'               => 'blogs#delete_blogs_index_bottom_ad_two',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_two
      match 'blog_index_images/delete_blogs_index_bottom_ad_three'               => 'blogs#delete_blogs_index_bottom_ad_three',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_three
      match 'blog_index_images/delete_blogs_index_side_ad'                     => 'blogs#delete_blogs_index_side_ad',              :via => [:delete],        :as => :delete_blogs_index_side_ad

      match '/press_index_images' =>                                       'press#edit_images',             via: ['get'],          :as => 'press_index_images'
      match '/press_index_images/update' =>                                'press#update_images',             via: ['patch'],          :as => 'press_index_images_update'

      match '/edit_press_page' =>                                       'press#edit_press_page',             via: ['get'],          :as => 'edit_press_page'
      match '/update_press_page' =>                                'press#update_press_page',             via: ['patch'],          :as => 'update_press_page'

app/models/event.rb
class Event < ApplicationRecord
  has_many :faqs, dependent: :destroy
  has_and_belongs_to_many :partners
  before_save :title_url_it
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  # has_many :images, dependent: :destroy
  # accepts_nested_attributes_for :images, allow_destroy: true

  has_many :images, as: :imageable, :class_name => "Event::Asset", dependent: :destroy

    Paperclip.interpolates :id do |attachment, style|
      attachment.instance.id
    end

    has_attached_file :cover_image, 
    :preserve_files => false,
    :path => "#{Rails.env}/Event/:id/cover_image/:style/:filename",
    :styles => { 
      :medium => ["295x342#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :cover_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true



    has_attached_file :icon, 
    :preserve_files => false,
    :path => "#{Rails.env}/Event/:id/icon/:style/:filename",
    :styles => { 
      :medium => ["150x150#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :icon, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true


    
    has_attached_file :main_image, 
    :preserve_files => false,
    :path => "#{Rails.env}/Event/:id/main_image/:style/:filename",
    :styles => { 
      :medium => ["262x175#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :main_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true




    has_attached_file :side_ad_one_image, 
    :preserve_files => false,
    :path => "#{Rails.env}/Event/:id/side_ad_one_image/:style/:filename",
    :styles => { 
      :medium => ["160x600#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :main_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }



    has_attached_file :ad_one_image, 
    :preserve_files => false,
    :path => "#{Rails.env}/Event/:id/ad_one_image/:style/:filename",
    :styles => { 
      :medium => ["300x250#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :main_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }



    has_attached_file :ad_two_image, 
    :preserve_files => false,
    :path => "#{Rails.env}/Event/:id/ad_two_image/:style/:filename",
    :styles => { 
      :medium => ["300x250#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :main_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }



    has_attached_file :ad_three_image, 
    :preserve_files => false,
    :path => "#{Rails.env}/Event/:id/ad_three_image/:style/:filename",
    :styles => { 
      :medium => ["300x250#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :main_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }



  def title_url_it
    # mytitle = event_date.strftime("%Y-%m-%d")
    # mytitle += "-" + city.downcase.squish.parameterize
    # self.title_for_slug = mytitle

    self.title_for_slug = city.downcase.squish.parameterize
  end

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  require 'will_paginate/array'
  before_action :set_event, only: [:show]

  def index
    @myevents = Event.all
    upcoming_events = Event.where("event_date >= ?", Date.today).order(event_date: :asc)
    past_events = Event.where("event_date < ?", Date.today).order(event_date: :asc)
    events = upcoming_events.to_a << past_events.to_a
    events.flatten!
    @events = events.paginate(:page => params[:page], :per_page => 6)

    @eventindex = EventIndex.first
  end

  def show
    @partners = @event.partners
    @images = @event.images.order(position: :asc)
    
    event = Faq.where.not(answer: nil).first.event
    @default_faq = Faq.where.not(answer: nil).where(event: event)
  end


  private

    def set_event
      @event = Event.find_by(title_for_slug: params[:title_for_slug])
    end

end

app/views/admin/events/_event_image.html.erb
<% if img.id.present? %>
<div id="event_image_<%= img.id %>" class="col-md-4 col-sm-6 item-img mb20" style="position: relative;">
  <img src="<%= img.pic.url(:medium) %>" alt="" class="img-responsive" width="100%" />
  <%= link_to "X", admin_event_image_delete_path(@event.title_for_slug, img.id.to_s),:method=>'delete', style: "position: absolute; top: 0px; right: 24px; color: red; font-size: 24px;", :remote=>true,:data=>{:confirm=>"Are you sure?"} %>
</div>
<% end %>

app/views/admin/events/edit.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Edit Event</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">
              <%= form_for(@event, :url => (admin_update_event_url(@event.title_for_slug)), :html => { :multipart => true }) do |f| %>
                <% if @event.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

                    <ul>
                    <% @event.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group">
                  <%= f.label :city %>
                  <%= f.text_field :city, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :cover_image %>
                  <%= "<br>".html_safe if @event.cover_image.present? %>
                  <%= image_tag(@event.cover_image.url(:medium), width: "180px") if @event.cover_image.present? %>
                  <%= "<br><br>".html_safe if @event.cover_image.present? %>                  
                  <%= f.file_field :cover_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :main_image %>
                  <%= "<br>".html_safe if @event.main_image.present? %>
                  <%= image_tag(@event.main_image.url(:medium), width: "180px") if @event.main_image.present? %>
                  <%= "<br><br>".html_safe if @event.main_image.present? %> 
                  <%= f.file_field :main_image, class: "form-control" %>
                </div>
                
                <div class="form-group">
                  <%= f.label :video_link %>
                  <%= f.text_field :video_link, class: "form-control" %>
                </div>
                
                <div class="form-group">
                  <%= f.label :icon %>
                  <%= f.file_field :icon, class: "form-control" %>
                </div>
                
                <div class="form-group">
                  <%= f.label :event_date %>
                  <%= f.date_field :event_date, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :event_description %>
                  <%= f.cktext_area :event_description, class: "form-control ckeditor", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :address %>
                  <%= f.text_field :address, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :location_description %>
                  <%= f.cktext_area :location_description, class: "form-control ckeditor", required: true %>
                </div>

                <br>
                <div class="form-group">
                  <%= f.label :partners %><br><br>
                  <%= f.collection_check_boxes(:partner_ids, Partner.all, :id, :name) do |b| %>
                      <%= b.label class:"label-checkbox" do%>
                       <%=b.check_box + b.text%>
                      <%end%>
                  <% end %>
                </div>
                <br>

                <div class="form-group">
                  <%= f.label :agenda_description %>
                  <%= f.cktext_area :agenda_description, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label "Purchase link" %>
                  <%= f.text_field :eventbrite_link, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad_one_image %>
                  <%= "<br>".html_safe if @event.side_ad_one_image.present? %>
                  <%= image_tag(@event.side_ad_one_image.url(:medium), width: "180px") if @event.side_ad_one_image.present? %>
                  <%= "<br><br>".html_safe if @event.side_ad_one_image.present? %>                   
                  <%= f.file_field :side_ad_one_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad_one_link %>
                  <%= f.text_field :side_ad_one_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :ad_one_image %>
                  <%= "<br>".html_safe if @event.ad_one_image.present? %>
                  <%= image_tag(@event.ad_one_image.url(:medium), width: "180px") if @event.ad_one_image.present? %>
                  <%= "<br><br>".html_safe if @event.ad_one_image.present? %>                   
                  <%= f.file_field :ad_one_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :ad_one_link %>
                  <%= f.text_field :ad_one_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :ad_two_image %>
                  <%= "<br>".html_safe if @event.ad_two_image.present? %>
                  <%= image_tag(@event.ad_two_image.url(:medium), width: "180px") if @event.ad_two_image.present? %>
                  <%= "<br><br>".html_safe if @event.ad_two_image.present? %>    
                  <%= f.file_field :ad_two_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :ad_two_link %>
                  <%= f.text_field :ad_two_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :ad_three_image %>
                  <%= "<br>".html_safe if @event.ad_three_image.present? %>
                  <%= image_tag(@event.ad_three_image.url(:medium), width: "180px") if @event.ad_three_image.present? %>
                  <%= "<br><br>".html_safe if @event.ad_three_image.present? %>  
                  <%= f.file_field :ad_three_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :ad_three_link %>
                  <%= f.text_field :ad_three_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_title %>
                  <%= f.text_field :meta_title, class: "form-control", required: true %>
                </div>
                
                <div class="form-group">
                  <%= f.label :meta_description %>
                  <%= f.text_field :meta_description, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>

          
          <div class="row mt70">
            <div class="col-md-4" style="position: relative;">
              <p><%= "Bottom ad one" if @event.ad_one_image.present? %></p>
              <%= image_tag(@event.ad_one_image.url(:medium), class: "img-responsive", width: '100%') if @event.ad_one_image.present? %>
              <span class="fts20 color-red" style="position: absolute; top: 20px; right:22px; color: red;"><%= link_to 'X', admin_delete_ad_one_image_path, style: "color: red;", method: :delete if @event.ad_one_image.present? %></span>
              <br><br>
            </div>
            <div class="col-md-4" style="position: relative;">
              <p><%= "Bottom ad two" if @event.ad_two_image.present? %></p>
              <%= image_tag(@event.ad_two_image.url(:medium), class: "img-responsive", width: '100%') if @event.ad_two_image.present? %>
              <span class="fts20 color-red" style="position: absolute; top: 20px; right:22px; color: red;"><%= link_to 'X', admin_delete_ad_two_image_path, style: "color: red;", method: :delete if @event.ad_two_image.present? %></span>
              <br><br>
            </div>
            <div class="col-md-4" style="position: relative;">
              <p><%= "Bottom ad three" if @event.ad_three_image.present? %></p>
              <%= image_tag(@event.ad_three_image.url(:medium), class: "img-responsive", width: '100%') if @event.ad_three_image.present? %>
              <span class="fts20 color-red" style="position: absolute; top: 20px; right:22px; color: red;"><%= link_to 'X', admin_delete_ad_three_image_path, style: "color: red;", method: :delete if @event.ad_three_image.present? %></span>
              <br><br>
            </div>
            <div class="col-md-4" style="position: relative;">
              <p><%= "Side ad" if @event.side_ad_one_image.present? %></p>
              <%= image_tag(@event.side_ad_one_image.url(:medium), class: "img-responsive", width: '100%') if @event.side_ad_one_image.present? %>
              <span class="fts20 color-red" style="position: absolute; top: 20px; right:22px; color: red;"><%= link_to 'X', admin_delete_side_ad_one_image_path, style: "color: red;", method: :delete if @event.side_ad_one_image.present? %></span>
              <br><br>
            </div>
          </div>

        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->

<style>
  .label-checkbox{
    margin-right: 20px;
  }
  .label-checkbox input{
    margin-right: 5px;
  }
</style>


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/events/event_image.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>
           
            <div class="row">

                <div class="col-sm-12 text-center mb35">

                    <h1 class="mb30"><%= @event.city.capitalize %> Slideshow Images</h1>

                    <%= form_for(@event_image, url:  admin_event_image_create_path(@event.title_for_slug), :html => { :multipart => true }) do |f| %>
                      <% if @event_image.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@event_image.errors.count, "error") %> prohibited this gallery image from being saved:</h2>
                          <ul>
                          <% @event_image.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>
                      <% end %>

                      <div class="form-group">
                        <%= f.hidden_field :imageable_type, value: 'Event'  %>
                        <%= f.hidden_field :imageable_id, value: @event.id  %>
                        <div class="dropzone" id="event_dropzone">
                          <%= f.label :pic, "Add Images", class: "btn btn-primary" %>
                          <%= f.file_field :pic, multiple: true, name: "event_image[pic]", class: "hide", required: true %>  
                        </div>
                      </div>

                      <!-- This is the progress bar showing the upload -->
                      <script id="template-upload" type="text/x-tmpl">
                        <div class="upload">
                          {%= "Uploading " + o.name + " (this bar will disappear once upload is complete)"%}
                          <div class="progress"><div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:0%;"></div></div>
                        </div>
                      </script>

                      <div class="form-group">
                        <%= f.submit "Upload", class: "form-control btn btn-primary hide" %>
                      </div>
                    <% end %>

                  </div>

                  <div id="event_images" data-update-url="<%= admin_event_image_sort_path %>">
                    <% @event_images.each do | img | %>
                      <%= render partial: 'event_image', locals: {img: img} %>
                    <% end %>
                  </div>

          </div>


        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>



<style>
  .dropzone {
    text-align: center;
    /*margin-top: 20px;*/
    padding-top: 30px;
    padding-bottom: 30px;
     border: 2px dashed #ddd;
  }
  .hide {
    display: none;
  }
  #event_images img:hover {
    cursor: move;
  }
  .x_delete:hover {
    cursor: pointer;
  }
</style>

app/views/admin/events/event_image_delete.js.erb
$("#event_image_<%= @event_image.id %>").remove();

app/views/admin/events/index.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">List events &nbsp;<a href="/admin/events/new" class="btn btn-primary">Add new</a></h1>
        
          <div>
              <% @events.each do |event| %>
                <div class="row mt20">
                    <div class="col-md-3 col-sm-4">
                      <%= image_tag(event.cover_image.url(:medium), class:'img-responsive') if event.main_image.present?%>
                    </div>

                    <div class="col-md-9 col-sm-8">
                      <h4 class=""><%= event.city %></h4>

                      <p class="small"><%= event.event_date.strftime("%B %d, %Y") %></p>

                      <div class="mt15 mb15">
                        <%= HTML_Truncator.truncate(event.event_description, 50).html_safe %>
                      </div>

                      <%= link_to 'Edit', admin_edit_event_path(event.title_for_slug), class:"btn btn-warning" %>

                      <%= link_to 'Destroy', admin_destroy_event_path(event.title_for_slug), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                </div>
                <hr>
              <% end %>
          </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

<%#= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@listing.latitude}%2C#{@listing.longitude}" %>