config/routes.rb
Rails.application.routes.draw do
  # require "admin_constraint"
  # mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new
  mount Ckeditor::Engine => "/ckeditor"
  
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  # devise_for :users
  devise_for :users, controlllers: {registrations: "registrations"}

  # devise_scope :user do 
  #   get "/admin" => "devise/sessions#new" 

  root 'pages#home'
  # match '/our-events' =>               'events#our_events',             via: ['get'],          :as => 'our_events'
  # match '/events/houston' =>               'events#houston',             via: ['get'],          :as => 'houston'
  # match '/events/austin' =>               'events#austin',             via: ['get'],          :as => 'austin'
  # match '/events/orlando' =>               'events#orlando',             via: ['get'],          :as => 'orlando'
  # match '/events/atlanta' =>               'events#atlanta',             via: ['get'],          :as => 'atlanta'
  # match '/events/cincinnati' =>               'events#cincinnati',             via: ['get'],          :as => 'cincinnati'
  # match '/events/dc' =>               'events#dc',             via: ['get'],          :as => 'dc'
  # match '/events/philadelphia' =>               'events#philadelphia',             via: ['get'],          :as => 'philadelphia'
  # match '/events/pittsburgh' =>               'events#pittsburgh',             via: ['get'],          :as => 'pittsburgh'
  # match '/events/salt-lake-city' =>               'events#saltlakecity',             via: ['get'],          :as => 'saltlakecity'
  # match '/events/south-florida' =>               'events#southflorida',             via: ['get'],          :as => 'southflorida'
  # match '/events/tampa-bay' =>               'events#tampabay',             via: ['get'],          :as => 'tampabay'

  match '/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
  match '/about-amy' =>                 'pages#about_amy',               via: ['get'],          :as => 'pages_about_amy'
  match '/partner-with-us' =>                      'pages#partner_with_us',         via: ['get'],          :as => 'pages_partner_with_us'

  match "/contacts"              =>        "contacts#create",              via: [:post]

  resources :users, except: [:create, :update]
  post 'create_user' => 'users#create', as: :create_user
  patch 'update_user/:id' => 'users#update', as: :update_user


  #########################################
  #==blogs url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    get "/blogs/categories", to: "blogs#index"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"

    get "blogs/categories/:category_slug", to: "blogs#index_category", as: "index_category"

  #########################################
  #==press url for press model
  #########################################
    # get "/press", to: "press#index", as: :press_index
    get "/press", to: "press#press_page", as: :press_page
    get "press/:title_for_slug", to: "press#show", as: "press"

  #########################################
  #==events url for events model
  #########################################
    get "/events", to: "events#index", as: :events
    get "events/:title_for_slug", to: "events#show", as: "event"
  
  #########################################
  #==partners url for partner model
  #########################################
    # get "/featured-partners", to: "partners#featured_partners"

    get "/partners", to: "partners#index", as: :partners
    get "/partners/:title_for_slug", to: "partners#show", as: :partner


    # get "/partners/la-croix", to: "partners#la_croix", as: :la_croix
    # get "/partners/cribs-for-kids", to: "partners#cribs_for_kids", as: :cribs_for_kids

    # get "partners/:title_for_slug", to: "partners#show", as: "partner"





  # match '/events'              =>        'events#index',              via: [:get],            :as => 'events'
  # match '/events/show'              =>        'events#show',              via: [:get],            :as => 'event'






  ############## ADMIN SECTION ############

  namespace :admin do
      match '/' =>                                'pages#admin',             via: ['get'],          :as => 'pages_admin'

      match '/pages/home' =>                      'pages#home',             via: ['get'],          :as => 'pages_home'
      match '/pages/home/update' =>                      'pages#home_update',             via: ['patch'],          :as => 'pages_home_update'
      match '/pages/home/delete_home_page_bottom_ad_one' =>                      'pages#delete_home_page_bottom_ad_one',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_one'
      match '/pages/home/delete_home_page_bottom_ad_two' =>                      'pages#delete_home_page_bottom_ad_two',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_two'
      match '/pages/home/delete_home_page_bottom_ad_three' =>                      'pages#delete_home_page_bottom_ad_three',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_three'


      match '/pages/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
      match '/pages/about-moabs/update' =>               'pages#about_moabs_update',             via: ['patch'],          :as => 'pages_about_moabs_update'


      match '/pages/about-amy' =>                 'pages#about_amy',             via: ['get'],          :as => 'pages_about_amy'
      match '/pages/about-amy/update' =>                 'pages#about_amy_update',             via: ['patch'],          :as => 'pages_about_amy_update'
      match '/pages/about-amy/delete_about_amy_bottom_ad_one' =>                      'pages#delete_about_amy_bottom_ad_one',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_one'
      match '/pages/about-amy/delete_about_amy_bottom_ad_two' =>                      'pages#delete_about_amy_bottom_ad_two',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_two'
      match '/pages/about-amy/delete_about_amy_bottom_ad_three' =>                      'pages#delete_about_amy_bottom_ad_three',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_three'



      match '/pages/partner-with-us' =>                      'pages#partner_with_us',             via: ['get'],          :as => 'pages_partner_with_us'
      match '/pages/partner-with-us/update' =>                      'pages#partner_with_us_update',             via: ['patch'],          :as => 'pages_partner_with_us_update'


      match '/event_index_images' =>                                       'events#edit_images',             via: ['get'],          :as => 'event_index_images'
      match '/event_index_images/update' =>                                'events#update_images',             via: ['patch'],          :as => 'event_index_images_update'


      match 'event_index_images/delete_event_index_bottom_ad_one'               => 'events#delete_event_index_bottom_ad_one',        :via => [:delete],        :as => :delete_event_index_bottom_ad_one
      match 'event_index_images/delete_event_index_bottom_ad_two'               => 'events#delete_event_index_bottom_ad_two',        :via => [:delete],        :as => :delete_event_index_bottom_ad_two
      match 'event_index_images/delete_event_index_bottom_ad_three'               => 'events#delete_event_index_bottom_ad_three',        :via => [:delete],        :as => :delete_event_index_bottom_ad_three
      match 'event_index_images/delete_event_index_side_ad_one'                     => 'events#delete_event_index_side_ad_one',              :via => [:delete],        :as => :delete_event_index_side_ad_one
      match 'event_index_images/delete_event_index_side_ad_two'                     => 'events#delete_event_index_side_ad_two',              :via => [:delete],        :as => :delete_event_index_side_ad_two





      match '/blog_index_images' =>                                       'blogs#edit_images',             via: ['get'],          :as => 'blog_index_images'
      match '/blog_index_images/update' =>                                'blogs#update_images',             via: ['patch'],          :as => 'blog_index_images_update'

      match 'blog_index_images/delete_blogs_index_bottom_ad_one'               => 'blogs#delete_blogs_index_bottom_ad_one',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_one
      match 'blog_index_images/delete_blogs_index_bottom_ad_two'               => 'blogs#delete_blogs_index_bottom_ad_two',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_two
      match 'blog_index_images/delete_blogs_index_bottom_ad_three'               => 'blogs#delete_blogs_index_bottom_ad_three',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_three
      match 'blog_index_images/delete_blogs_index_side_ad'                     => 'blogs#delete_blogs_index_side_ad',              :via => [:delete],        :as => :delete_blogs_index_side_ad

      match '/press_index_images' =>                                       'press#edit_images',             via: ['get'],          :as => 'press_index_images'
      match '/press_index_images/update' =>                                'press#update_images',             via: ['patch'],          :as => 'press_index_images_update'

      match '/edit_press_page' =>                                       'press#edit_press_page',             via: ['get'],          :as => 'edit_press_page'
      match '/update_press_page' =>                                'press#update_press_page',             via: ['patch'],          :as => 'update_press_page'

app/models/partner.rb
class Partner < ApplicationRecord
  has_and_belongs_to_many :events
  before_save :title_url_it

  has_many :images, as: :imageable, :class_name => "Partner::Asset", dependent: :destroy

  Paperclip.interpolates :id do |attachment, style|
      attachment.instance.id
    end

    has_attached_file :main_image, 
    :preserve_files => false,
    :path => "#{Rails.env}/Partner/:id/main_image/:style/:filename",
    :styles => { 
      :small => ["262x205#", :jpg], 
      :medium => ["300x300#", :jpg], 
      :large => ["1200x800#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

    validates_attachment :main_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

  def title_url_it
    self.title_for_slug = name.downcase.squish.parameterize
  end

end

app/models/partner/asset.rb
class Partner::Asset < Image

  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/slideshow/:style/:filename",
    :styles => { 
      :medium => ["350x250#", :jpg], 
      :large => ["1200x800#", :jpg],
      :huge => ["1600x663#", :jpg],
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true


  # # after_create :set_position
  # after_create_commit :set_position

  # def set_position
  #   self.position = Image.where(imageable_type: self.imageable_type, imageable_id: self.imageable_id).maximum(:position).to_i + 1
  #   # self.save
  # end

end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < ApplicationController
  before_action :set_partner, only: [:edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @partners = Partner.all
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    if @partner.save
      redirect_to admin_partners_path, notice: 'Partner was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    # if @partner.update(category_params)
    #   redirect_to admin_partners_path, notice: 'Category was successfully updated.'
    # else
    #   render :edit
    # end

    if !params[:partner][:main_image].present?
      if @partner.update(partner_without_image_params)
        redirect_to admin_partners_path, notice: 'Partner was successfully updated.'
      else
        render :edit
      end
    else
      @partner.main_image.destroy
      if @partner.update(partner_params)
        redirect_to admin_partners_path, notice: 'Partner was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    @partner.destroy
    redirect_to admin_partners_path, notice: 'Partner was successfully destroyed.'
  end


  ##============================================================##
  ## Images
  ##============================================================##
  def images
    @partners = Partner.all
  end

  def partner_image
    @partner = Partner.find_by(title_for_slug: params[:title_for_slug])
    @partner_images = @partner.images.order(position: :asc)
    @partner_image = @partner.images.new
  end

  def partner_image_create
    @partner = Partner.find_by(title_for_slug: params[:title_for_slug])
    @partner_image = @partner.images.new(partner_image_params)
    @partner_image.save
  end

  def partner_image_delete
    @partner = Partner.find_by(title_for_slug: params[:title_for_slug])
    @partner_image = @partner.images.where(id: params[:img_id]).first
    @partner_image.destroy
  end

  def partner_image_sort
    data_sql_format = ""
      params[:partner_image].each_with_index do | img_id, index |
        data_sql_format << "(#{img_id},#{index +1}),"
      end

      # This will do it in a single database update query O(1), however it requires O(n) calculations to format the data in a manner postgres likes it

      data_sql_format = data_sql_format[0...-1] # this is to remove the last comma, # i.e., data_sql_format = (1,1),(3,2),(2,3),(4,4) 

      ActiveRecord::Base.connection.execute(
        "update images as m set
            position = c.position
        from (values
            #{data_sql_format}
        ) as c(id, position) 
        where c.id = m.id
      ")

      # render nothing: true # deprecated in rails 5.1 use below
      head :ok
  end

  private

    def set_partner
      @partner = Partner.find_by(title_for_slug: params[:title_for_slug])
    end

    def partner_params
      params.require(:partner).permit(:name, :title_for_slug, :main_image, :weblink, :description, :meta_description, :testimonial, :testimonial_author)
    end

    def partner_without_image_params
      params.require(:partner).permit(:name, :title_for_slug, :weblink, :description, :meta_description, :testimonial, :testimonial_author)
    end

    def partner_image_params
      params.require(:partner_image).permit!
    end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show]

  def index
    @partners = Partner.all
  end

  def show
    @images = @partner.images.order(position: :asc)
  end

  private

    def set_partner
      @partner = Partner.find_by(title_for_slug: params[:title_for_slug])
    end

end

app/views/admin/partners/_partner_image.html.erb
<% if img.id.present? %>
<div id="partner_image_<%= img.id %>" class="col-md-4 col-sm-6 item-img mb20" style="position: relative;">
  <img src="<%= img.pic.url(:medium) %>" alt="" class="img-responsive" width="100%" />
  <%= link_to "X", admin_partner_image_delete_path(@partner.title_for_slug, img.id.to_s),:method=>'delete', style: "position: absolute; top: 0px; right: 24px; color: red; font-size: 24px;", :remote=>true,:data=>{:confirm=>"Are you sure?"} %>
</div>
<% end %>

app/views/admin/partners/edit.html.erb
<% if current_user.try(:admin) || current_user.email.split("@")[0] == @partner.title_for_slug %>
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Edit Partner</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">

              <%= form_for(@partner, :url => (admin_update_partners_path(@partner.title_for_slug)), :html => { :multipart => true }) do |f| %>
                <% if @partner.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

                    <ul>
                    <% @partner.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <% if current_user.try(:admin) %>
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, class: "form-control", required: true %>
                </div>
                <% end %>
                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.cktext_area :description, class: "form-control ckeditor" %>
                </div>

                <div class="form-group">
                  <%= f.label :main_image %>
                  <%= "<br>".html_safe if @partner.main_image.present? %>
                  <%= image_tag(@partner.main_image.url(:medium), width: "180px") if @partner.main_image.present? %>
                  <%= "<br><br>".html_safe if @partner.main_image.present? %>
                  <%= f.file_field :main_image, style: "padding: 4px;" %>
                </div>

                <div class="form-group">
                  <%= f.label :weblink %>
                  <%= f.text_field :weblink, class: "form-control", required: true %>
                </div>
                
                <div class="form-group">
                  <%= f.label :testimonial %>
                  <%= f.text_field :testimonial, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :testimonial_author %>
                  <%= f.text_field :testimonial_author, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_description %>
                  <%= f.text_field :meta_description, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>
<% end %>

app/views/admin/partners/images.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>
     
          <div>
              <% @partners.each do |partner| %>
              <% if !current_user.try(:admin) && current_user.email.split("@")[0] == partner.title_for_slug %>
                <div class="row mt20">
                    <div class="col-md-3 col-sm-4">
                      <%= image_tag(partner.main_image.url(:medium), class:'img-responsive') %>
                    </div>

                    <div class="col-md-9 col-sm-8">
                      <h4 class=""><%= partner.name %></h4>

                      <%= link_to 'Edit Image Slides', admin_partner_image_path(partner.title_for_slug), class:"btn btn-warning" %>

                    </div>

                </div>
                <hr>
              <% elsif current_user.try(:admin) %>
                <div class="row mt20">
                    <div class="col-md-3 col-sm-4">
                      <%= image_tag(partner.main_image.url(:medium), class:'img-responsive') %>
                    </div>

                    <div class="col-md-9 col-sm-8">
                      <h4 class=""><%= partner.name %></h4>

                      <%= link_to 'Edit Image Slides', admin_partner_image_path(partner.title_for_slug), class:"btn btn-warning" %>

                    </div>

                </div>
                <hr>
              <% end %>
              <% end %>
          </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/partners/index.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <% if current_user.try(:admin) %>
          <h1 class="mb30">List partners &nbsp;<a href="/admin/partners/new" class="btn btn-primary">Add new</a></h1>
        <% end %>

          <div>
              <% @partners.each do |partner| %>
                <% if !current_user.try(:admin) && current_user.email.split("@")[0] == partner.title_for_slug %>
                <div class="row mt20">
                    <div class="col-md-3 col-sm-4">
                      <%= image_tag(partner.main_image.url(:medium), class:'img-responsive') if partner.main_image.present?%>
                    </div>

                    <div class="col-md-9 col-sm-8">
                      <h4 class=""><%= partner.name %></h4>

                      <%= link_to 'Edit', admin_edit_partners_path(partner.title_for_slug), class:"btn btn-warning" %>

                      <%= link_to 'Destroy', admin_destroy_partners_path(partner.title_for_slug), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin) %>
                    </div>
                </div>
                <hr>
                <% elsif current_user.try(:admin) %>
                  <div class="row mt20">
                      <div class="col-md-3 col-sm-4">
                        <%= image_tag(partner.main_image.url(:medium), class:'img-responsive') if partner.main_image.present?%>
                      </div>

                      <div class="col-md-9 col-sm-8">
                        <h4 class=""><%= partner.name %></h4>

                        <%= link_to 'Edit', admin_edit_partners_path(partner.title_for_slug), class:"btn btn-warning" %>

                        <%= link_to 'Destroy', admin_destroy_partners_path(partner.title_for_slug), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin) %>
                      </div>
                  </div>
                  <hr>
                <% end %>
              <% end %>
          </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>



















<% if false %>
<section class="bg-light-grey">

  <div class="container">
  <%= link_to 'New Blog', new_blog_path, class:"btn btn-primary" if current_user.try(:admin?)%>

    <% @blogs.each do |blog| %>
    <div class="row">
      
      <div class="col-sm-4 mb15">
        <%= link_to blog_path(blog.title_for_slug) do %> 
          <%= image_tag(blog.images[0].pic.url(:medium), class:'img-responsive') if blog.images.present?%>
        <% end %>
      </div>
      <div class="col-sm-8">
        <h4><%= link_to blog.title, blog_path(blog.title_for_slug), class: 'h2' %></h4>
        <p><%= HTML_Truncator.truncate(blog.content_index, 150).html_safe %></p>
        <div class="mt30 pull-right">
          <%= link_to 'Read More', blog_path(blog.title_for_slug), class:"btn btn-primary" %>
          <%= link_to 'Edit', edit_blog_path(blog.title_for_slug), class:"btn btn-primary" if current_user.try(:admin?)%>
          <%= link_to 'Destroy', blog_path(blog.title_for_slug), class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?) %>
        </div>
      </div>
    </div>
  <% end %>

  </div>
  
</section>
<% end %>

app/views/admin/partners/new.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Create Partner</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">

              <%= form_for(@partner, :url => (admin_partners_url), :html => { :multipart => true }) do |f| %>
                <% if @partner.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

                    <ul>
                    <% @partner.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.cktext_area :description, class: "form-control ckeditor" %>
                </div>

                <div class="form-group">
                  <%= f.label :main_image %>
                  <%= f.file_field :main_image, style: "padding: 4px;", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :weblink %>
                  <%= f.text_field :weblink, class: "form-control", required: true %>
                </div>
                
                <div class="form-group">
                  <%= f.label :testimonial %>
                  <%= f.text_field :testimonial, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :testimonial_author %>
                  <%= f.text_field :testimonial_author, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_description %>
                  <%= f.text_field :meta_description, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/partners/partner_image.html.erb
<% if current_user.try(:admin) || current_user.email.split("@")[0] == @partner.title_for_slug %>

<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>
           
            <div class="row">

                <div class="col-sm-12 text-center mb35">

                    <h1 class="mb30"><%= @partner.name %> Slideshow Images</h1>

                    <%= form_for(@partner_image, url:  admin_partner_image_create_path(@partner.title_for_slug), :html => { :multipart => true }) do |f| %>
                      <% if @partner_image.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@partner_image.errors.count, "error") %> prohibited this gallery image from being saved:</h2>
                          <ul>
                          <% @partner_image.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>
                      <% end %>

                      <div class="form-group">
                        <%= f.hidden_field :imageable_type, value: 'Partner'  %>
                        <%= f.hidden_field :imageable_id, value: @partner.id  %>
                        <div class="dropzone" id="partner_dropzone">
                          <%= f.label :pic, "Add Images", class: "btn btn-primary" %>
                          <%= f.file_field :pic, multiple: true, name: "partner_image[pic]", class: "hide", required: true %>  
                        </div>
                      </div>

                      <!-- This is the progress bar showing the upload -->
                      <script id="template-upload" type="text/x-tmpl">
                        <div class="upload">
                          {%= "Uploading " + o.name + " (this bar will disappear once upload is complete)"%}
                          <div class="progress"><div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:0%;"></div></div>
                        </div>
                      </script>

                      <div class="form-group">
                        <%= f.submit "Upload", class: "form-control btn btn-primary hide" %>
                      </div>
                    <% end %>

                  </div>

                  <div id="partner_images" data-update-url="<%= admin_partner_image_sort_path %>">
                    <% @partner_images.each do | img | %>
                      <%= render partial: 'partner_image', locals: {img: img} %>
                    <% end %>
                  </div>

          </div>


        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>



<style>
  .dropzone {
    text-align: center;
    /*margin-top: 20px;*/
    padding-top: 30px;
    padding-bottom: 30px;
     border: 2px dashed #ddd;
  }
  .hide {
    display: none;
  }
  #partner_images img:hover {
    cursor: move;
  }
  .x_delete:hover {
    cursor: pointer;
  }
</style>
<% end %>

app/views/admin/partners/partner_image_delete.js.erb
$("#partner_image_<%= @partner_image.id %>").remove();