config/routes.rb
Rails.application.routes.draw do
  # require "admin_constraint"
  # mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new
  mount Ckeditor::Engine => "/ckeditor"
  
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  # devise_for :users
  devise_for :users, controlllers: {registrations: "registrations"}

  # devise_scope :user do 
  #   get "/admin" => "devise/sessions#new" 

  root 'pages#home'
  # match '/our-events' =>               'events#our_events',             via: ['get'],          :as => 'our_events'
  # match '/events/houston' =>               'events#houston',             via: ['get'],          :as => 'houston'
  # match '/events/austin' =>               'events#austin',             via: ['get'],          :as => 'austin'
  # match '/events/orlando' =>               'events#orlando',             via: ['get'],          :as => 'orlando'
  # match '/events/atlanta' =>               'events#atlanta',             via: ['get'],          :as => 'atlanta'
  # match '/events/cincinnati' =>               'events#cincinnati',             via: ['get'],          :as => 'cincinnati'
  # match '/events/dc' =>               'events#dc',             via: ['get'],          :as => 'dc'
  # match '/events/philadelphia' =>               'events#philadelphia',             via: ['get'],          :as => 'philadelphia'
  # match '/events/pittsburgh' =>               'events#pittsburgh',             via: ['get'],          :as => 'pittsburgh'
  # match '/events/salt-lake-city' =>               'events#saltlakecity',             via: ['get'],          :as => 'saltlakecity'
  # match '/events/south-florida' =>               'events#southflorida',             via: ['get'],          :as => 'southflorida'
  # match '/events/tampa-bay' =>               'events#tampabay',             via: ['get'],          :as => 'tampabay'

  match '/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
  match '/about-amy' =>                 'pages#about_amy',               via: ['get'],          :as => 'pages_about_amy'
  match '/partner-with-us' =>                      'pages#partner_with_us',         via: ['get'],          :as => 'pages_partner_with_us'

  match "/contacts"              =>        "contacts#create",              via: [:post]

  resources :users, except: [:create, :update]
  post 'create_user' => 'users#create', as: :create_user
  patch 'update_user/:id' => 'users#update', as: :update_user


  #########################################
  #==blogs url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    get "/blogs/categories", to: "blogs#index"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"

    get "blogs/categories/:category_slug", to: "blogs#index_category", as: "index_category"

  #########################################
  #==press url for press model
  #########################################
    # get "/press", to: "press#index", as: :press_index
    get "/press", to: "press#press_page", as: :press_page
    get "press/:title_for_slug", to: "press#show", as: "press"

  #########################################
  #==events url for events model
  #########################################
    get "/events", to: "events#index", as: :events
    get "events/:title_for_slug", to: "events#show", as: "event"
  
  #########################################
  #==partners url for partner model
  #########################################
    # get "/featured-partners", to: "partners#featured_partners"

    get "/partners", to: "partners#index", as: :partners
    get "/partners/:title_for_slug", to: "partners#show", as: :partner


    # get "/partners/la-croix", to: "partners#la_croix", as: :la_croix
    # get "/partners/cribs-for-kids", to: "partners#cribs_for_kids", as: :cribs_for_kids

    # get "partners/:title_for_slug", to: "partners#show", as: "partner"





  # match '/events'              =>        'events#index',              via: [:get],            :as => 'events'
  # match '/events/show'              =>        'events#show',              via: [:get],            :as => 'event'






  ############## ADMIN SECTION ############

  namespace :admin do
      match '/' =>                                'pages#admin',             via: ['get'],          :as => 'pages_admin'

      match '/pages/home' =>                      'pages#home',             via: ['get'],          :as => 'pages_home'
      match '/pages/home/update' =>                      'pages#home_update',             via: ['patch'],          :as => 'pages_home_update'
      match '/pages/home/delete_home_page_bottom_ad_one' =>                      'pages#delete_home_page_bottom_ad_one',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_one'
      match '/pages/home/delete_home_page_bottom_ad_two' =>                      'pages#delete_home_page_bottom_ad_two',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_two'
      match '/pages/home/delete_home_page_bottom_ad_three' =>                      'pages#delete_home_page_bottom_ad_three',             via: ['delete'],          :as => 'delete_home_page_bottom_ad_three'


      match '/pages/about-moabs' =>               'pages#about_moabs',             via: ['get'],          :as => 'pages_about_moabs'
      match '/pages/about-moabs/update' =>               'pages#about_moabs_update',             via: ['patch'],          :as => 'pages_about_moabs_update'


      match '/pages/about-amy' =>                 'pages#about_amy',             via: ['get'],          :as => 'pages_about_amy'
      match '/pages/about-amy/update' =>                 'pages#about_amy_update',             via: ['patch'],          :as => 'pages_about_amy_update'
      match '/pages/about-amy/delete_about_amy_bottom_ad_one' =>                      'pages#delete_about_amy_bottom_ad_one',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_one'
      match '/pages/about-amy/delete_about_amy_bottom_ad_two' =>                      'pages#delete_about_amy_bottom_ad_two',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_two'
      match '/pages/about-amy/delete_about_amy_bottom_ad_three' =>                      'pages#delete_about_amy_bottom_ad_three',             via: ['delete'],          :as => 'delete_about_amy_bottom_ad_three'



      match '/pages/partner-with-us' =>                      'pages#partner_with_us',             via: ['get'],          :as => 'pages_partner_with_us'
      match '/pages/partner-with-us/update' =>                      'pages#partner_with_us_update',             via: ['patch'],          :as => 'pages_partner_with_us_update'


      match '/event_index_images' =>                                       'events#edit_images',             via: ['get'],          :as => 'event_index_images'
      match '/event_index_images/update' =>                                'events#update_images',             via: ['patch'],          :as => 'event_index_images_update'


      match 'event_index_images/delete_event_index_bottom_ad_one'               => 'events#delete_event_index_bottom_ad_one',        :via => [:delete],        :as => :delete_event_index_bottom_ad_one
      match 'event_index_images/delete_event_index_bottom_ad_two'               => 'events#delete_event_index_bottom_ad_two',        :via => [:delete],        :as => :delete_event_index_bottom_ad_two
      match 'event_index_images/delete_event_index_bottom_ad_three'               => 'events#delete_event_index_bottom_ad_three',        :via => [:delete],        :as => :delete_event_index_bottom_ad_three
      match 'event_index_images/delete_event_index_side_ad_one'                     => 'events#delete_event_index_side_ad_one',              :via => [:delete],        :as => :delete_event_index_side_ad_one
      match 'event_index_images/delete_event_index_side_ad_two'                     => 'events#delete_event_index_side_ad_two',              :via => [:delete],        :as => :delete_event_index_side_ad_two





      match '/blog_index_images' =>                                       'blogs#edit_images',             via: ['get'],          :as => 'blog_index_images'
      match '/blog_index_images/update' =>                                'blogs#update_images',             via: ['patch'],          :as => 'blog_index_images_update'

      match 'blog_index_images/delete_blogs_index_bottom_ad_one'               => 'blogs#delete_blogs_index_bottom_ad_one',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_one
      match 'blog_index_images/delete_blogs_index_bottom_ad_two'               => 'blogs#delete_blogs_index_bottom_ad_two',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_two
      match 'blog_index_images/delete_blogs_index_bottom_ad_three'               => 'blogs#delete_blogs_index_bottom_ad_three',        :via => [:delete],        :as => :delete_blogs_index_bottom_ad_three
      match 'blog_index_images/delete_blogs_index_side_ad'                     => 'blogs#delete_blogs_index_side_ad',              :via => [:delete],        :as => :delete_blogs_index_side_ad

      match '/press_index_images' =>                                       'press#edit_images',             via: ['get'],          :as => 'press_index_images'
      match '/press_index_images/update' =>                                'press#update_images',             via: ['patch'],          :as => 'press_index_images_update'

      match '/edit_press_page' =>                                       'press#edit_press_page',             via: ['get'],          :as => 'edit_press_page'
      match '/update_press_page' =>                                'press#update_press_page',             via: ['patch'],          :as => 'update_press_page'

app/models/press/asset.rb
class Press::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :medium => ["300x190>", :jpg], 
      :large => ["1200x800#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end

app/controllers/admin/press_controller.rb
class Admin::PressController < ApplicationController
  before_action :set_press, only: [:edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @press = Press.order(pubdate: :desc)
  end

  def new
    @press = Press.new
  end

  def create
    @press = Press.new(press_params)
    if @press.save
      redirect_to admin_press_index_path, notice: 'press was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def edit_press_page
    @press_page = PressPage.first
  end

  def update_press_page
    @press_page = PressPage.first
    if @press_page.update(press_page_params)
      redirect_to admin_edit_press_page_path, notice: 'press was successfully updated.'
    else
      render :edit_press_page
    end
  end

  def update
    if @press.update(press_params)
      redirect_to admin_press_index_path, notice: 'press was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @press.destroy
    redirect_to admin_press_index_path, notice: 'press was successfully destroyed.'
  end

  def edit_images
    @press_index = PressIndex.first
  end

  def update_images
    @press_index = PressIndex.first
    if @press_index.update(press_index_params)
      redirect_to admin_press_index_images_path, notice: 'Press Index Images were successfully updated.'
    else
      render :edit_images
    end
  end





  def press_images
    @press_page = PressPage.first
    @press_images = @press_page.images.order(position: :asc)
    @press_image = @press_page.images.new
  end

  def press_image_create
    @press_page = PressPage.first
    @press_image = @press_page.images.new(press_image_params)
    @press_image.save
  end

  def press_image_delete
    @press_page = PressPage.first
    @press_image = @press_page.images.where(id: params[:img_id]).first
    @press_image.destroy
  end

  def press_image_sort
    data_sql_format = ""
      params[:press_image].each_with_index do | img_id, index |
        data_sql_format << "(#{img_id},#{index +1}),"
      end

      # This will do it in a single database update query O(1), however it requires O(n) calculations to format the data in a manner postgres likes it

      data_sql_format = data_sql_format[0...-1] # this is to remove the last comma, # i.e., data_sql_format = (1,1),(3,2),(2,3),(4,4) 

      ActiveRecord::Base.connection.execute(
        "update images as m set
            position = c.position
        from (values
            #{data_sql_format}
        ) as c(id, position) 
        where c.id = m.id
      ")

      # render nothing: true # deprecated in rails 5.1 use below
      head :ok
  end



  private

    def set_press
      @press = Press.find_by(title_for_slug: params[:title_for_slug])
    end

    def press_params
      params.require(:press).permit(:title, :content, :content_index, :title_for_slug, :main_image, :pubdate, :meta_description, :meta_keywords, :side_ad_link, :side_ad, :bottom_ad_one_link, :bottom_ad_one, :bottom_ad_two_link, :bottom_ad_two, :bottom_ad_three_link, :bottom_ad_three, images_attributes: [:id, :pic, :name, :primary, :_destroy])
    end

    def press_page_params
      # params.require(:press_page).permit(:main_image, :video_link, :description, :meta_keywords, :side_ad_link, :side_ad, :bottom_ad_one_link, :bottom_ad_one, :bottom_ad_two_link, :bottom_ad_two, :bottom_ad_three_link, :bottom_ad_three, images_attributes: [:id, :pic, :name, :primary, :_destroy])
      params.require(:press_page).permit(:main_image, :video_link, :description)
    end

    def press_image_params
      # params.require(:press_page).permit(:main_image, :video_link, :description, :meta_keywords, :side_ad_link, :side_ad, :bottom_ad_one_link, :bottom_ad_one, :bottom_ad_two_link, :bottom_ad_two, :bottom_ad_three_link, :bottom_ad_three, images_attributes: [:id, :pic, :name, :primary, :_destroy])
      params.require(:press_image).permit!
    end

    def press_index_params
      params.require(:press_index).permit(:bottom_ad_one, :bottom_ad_two, :bottom_ad_three, :bottom_ad_one_link, :bottom_ad_two_link, :bottom_ad_three_link, :side_ad, :side_ad_link)
    end

  end

app/controllers/press_controller.rb
class PressController < ApplicationController
  before_action :set_press, only: [:show]

  def index
    @press = Press.order(pubdate: :desc).page(params[:page]).per_page(4)
    @press_index = PressIndex.first
  end

  def show
  end

  def press_page
    @press_page = PressPage.first
    @images = @press_page.images.order(position: :asc)
  end

  private

  def set_press
    @press = Press.find_by(title_for_slug: params[:title_for_slug])
  end

end

app/views/admin/press/_press_image.html.erb
<% if img.id.present? %>
<div id="press_image_<%= img.id %>" class="col-md-4 col-sm-6 item-img mb20" style="position: relative;">
  <img src="<%= img.pic.url(:medium) %>" alt="" class="img-responsive" width="100%" />
  <%= link_to "X", admin_press_image_delete_path(img.id.to_s),:method=>'delete', style: "position: absolute; top: 0px; right: 24px; color: red; font-size: 24px;", :remote=>true,:data=>{:confirm=>"Are you sure?"} %>
</div>
<% end %>

app/views/admin/press/edit.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Edit Press</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">

              <%= form_for(@press, :url => (admin_update_press_path(@press.title_for_slug)), :html => { :multipart => true }) do |f| %>
                <% if @press.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@press.errors.count, "error") %> prohibited this press from being saved:</h2>

                    <ul>
                    <% @press.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :main_image %>
                  <%= f.file_field :main_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.cktext_area :content, class: "form-control ckeditor", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_description %>
                  <%= f.text_field :meta_description, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_keywords %>
                  <%= f.text_field :meta_keywords, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :pubdate %><br>
                  <%= f.date_field :pubdate, value: Date.today, class:'form-control', required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad_link %><br>
                  <%= f.text_field :side_ad_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad %><br>
                  <%= f.file_field :side_ad %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_one_link %><br>
                  <%= f.text_field :bottom_ad_one_link, class: "form-control"%>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_one %><br>
                  <%= f.file_field :bottom_ad_one %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two_link %><br>
                  <%= f.text_field :bottom_ad_two_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two %><br>
                  <%= f.file_field :bottom_ad_two %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three_link %><br>
                  <%= f.text_field :bottom_ad_three_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three %><br>
                  <%= f.file_field :bottom_ad_three %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/press/edit_images.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Edit Press Index Images</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">
              <%= form_for(@press_index, :url => admin_press_index_images_update_url, :html => { :multipart => true }) do |f| %>
                <% if @press_index.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@press_index.errors.count, "error") %> prohibited this Event Index Image from being saved:</h2>

                    <ul>
                    <% @press_index.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group">
                  <%= f.label :bottom_ad_one_link %>
                  <%= f.text_field :bottom_ad_one_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_one %>
                  <%= f.file_field :bottom_ad_one, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two_link %>
                  <%= f.text_field :bottom_ad_two_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two %>
                  <%= f.file_field :bottom_ad_two, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three_link %>
                  <%= f.text_field :bottom_ad_three_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three %>
                  <%= f.file_field :bottom_ad_three, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad_link %>
                  <%= f.text_field :side_ad_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad %>
                  <%= f.file_field :side_ad, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/press/edit_press_page.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Edit Press Page</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">

              <%= form_for(@press_page, :url => (admin_update_press_page_path), :html => { :multipart => true }) do |f| %>
                <% if @press_page.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@press_page.errors.count, "error") %> prohibited this press from being saved:</h2>

                    <ul>
                    <% @press_page.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group">
                  <%= f.label :main_image %>
                  <%= "<br>".html_safe if @press_page.main_image.present? %>
                  <%= image_tag(@press_page.main_image.url(:medium), width: "180px") if @press_page.main_image.present? %>
                  <%= "<br><br>".html_safe if @press_page.main_image.present? %>  
                  <%= f.file_field :main_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :video_link %>
                  <%= f.text_field :video_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.cktext_area :description, class: "form-control ckeditor" %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/press/index.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">List press &nbsp;<a href="/admin/press/new" class="btn btn-primary">Add new</a></h1>
        
          <div>
              <% @press.each do |press| %>
                <div class="row mt20">
                    <div class="col-md-3 col-sm-4">
                      <%= image_tag(press.main_image.url(:medium), class:'img-responsive') %>
                    </div>

                    <div class="col-md-9 col-sm-8">
                      <h4 class=""><%= press.title %></h4>

                      <p class="small"><%= press.pubdate.strftime("%B %d, %Y") %></p>

                      <div class="mt15 mb15">
                        <%= HTML_Truncator.truncate(press.content_index, 50).html_safe %>
                      </div>

                      <%= link_to 'Edit', admin_edit_press_path(press.title_for_slug), class:"btn btn-warning" %>

                      <%= link_to 'Destroy', admin_destroy_press_path(press.title_for_slug), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                </div>
                <hr>
              <% end %>
          </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>



















<% if false %>
<section class="bg-light-grey">

  <div class="container">
  <%= link_to 'New Blog', new_blog_path, class:"btn btn-primary" if current_user.try(:admin?)%>

    <% @blogs.each do |blog| %>
    <div class="row">
      
      <div class="col-sm-4 mb15">
        <%= link_to blog_path(blog.title_for_slug) do %> 
          <%= image_tag(blog.images[0].pic.url(:medium), class:'img-responsive') if blog.images.present?%>
        <% end %>
      </div>
      <div class="col-sm-8">
        <h4><%= link_to blog.title, blog_path(blog.title_for_slug), class: 'h2' %></h4>
        <p><%= HTML_Truncator.truncate(blog.content_index, 150).html_safe %></p>
        <div class="mt30 pull-right">
          <%= link_to 'Read More', blog_path(blog.title_for_slug), class:"btn btn-primary" %>
          <%= link_to 'Edit', edit_blog_path(blog.title_for_slug), class:"btn btn-primary" if current_user.try(:admin?)%>
          <%= link_to 'Destroy', blog_path(blog.title_for_slug), class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?) %>
        </div>
      </div>
    </div>
  <% end %>

  </div>
  
</section>
<% end %>

app/views/admin/press/new.html.erb
<div class="wrapper">

    <%= render 'admin/layouts/sidebar' %>
    
    <div id="content">

        <%= render 'admin/layouts/sidebar_topnav' %>

        <h1 class="mb30">Create Press</h1>
        
        <div>
          <div class="row">
            <div class="col-md-12">

              <%= form_for(@press, :url => (admin_press_url), :html => { :multipart => true }) do |f| %>
                <% if @press.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@press.errors.count, "error") %> prohibited this press from being saved:</h2>

                    <ul>
                    <% @press.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :main_image %>
                  <%= f.file_field :main_image, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.cktext_area :content, class: "form-control ckeditor", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_description %>
                  <%= f.text_field :meta_description, class: "form-control", required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :meta_keywords %>
                  <%= f.text_field :meta_keywords, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :pubdate %><br>
                  <%= f.date_field :pubdate, value: Date.today, class:'form-control', required: true %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad_link %><br>
                  <%= f.text_field :side_ad_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :side_ad %><br>
                  <%= f.file_field :side_ad %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_one_link %><br>
                  <%= f.text_field :bottom_ad_one_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_one %><br>
                  <%= f.file_field :bottom_ad_one %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two_link %><br>
                  <%= f.text_field :bottom_ad_two_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_two %><br>
                  <%= f.file_field :bottom_ad_two %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three_link %><br>
                  <%= f.text_field :bottom_ad_three_link, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :bottom_ad_three %><br>
                  <%= f.file_field :bottom_ad_three %>
                </div>

                <div class="form-group">
                  <%= f.submit "Submit", class: "form-control btn btn-primary" %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
        

    </div> <!-- content  -->

</div> <!-- wrapper  -->


<%= render 'admin/layouts/sidebar_styles_scripts' %>

app/views/admin/press/press_image_delete.js.erb
$("#press_image_<%= @press_image.id %>").remove();